on: push
name: Slack Notification Demo 1
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: partnerhero/action-webhook-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: devops-final-project
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
